name: Build x64
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore ./MirrorAudio.csproj
      - name: Build x64
        run: dotnet build ./MirrorAudio.csproj -c Release -p:PlatformTarget=x64 -p:GenerateRuntimeConfigurationFiles=true --nologo
      - name: Publish
        run: dotnet publish ./MirrorAudio.csproj -c Release -r win-x64 -p:PublishSingleFile=false --self-contained false -o out
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MirrorAudio-x64
          path: out/**
